# GitLab Ci Runner
gitlab-runner:
  image: gitlab/gitlab-runner:latest
  restart: always
  tty: true
  volumes:
    - /srv/gitlab-runner/config:/etc/gitlab-runner
    - /var/run/docker.sock:/var/run/docker.sock
  environment:
    - REGISTER_NON_INTERACTIVE=true
    - CI_SERVER_URL=http://[GitLabのIPアドレス]/ci
    - REGISTRATION_TOKEN=[トークン]
    - RUNNER_EXECUTOR=docker
    - RUNNER_TAG_LIST=[タグ名]
    - RUNNER_NAME=[ランナー名]
    - DOCKER_IMAGE=docker:latest
    - DOCKER_VOLUMES=/var/run/docker.sock:/var/run/docker.sock
    - REGISTER_RUN_UNTAGGED=true
    - REGISTER_LOCKED=false
